// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Pv95IQ8xrN2OyQbH6tPntnIRSLKZaZk',
    appId: '1:372532983327:web:8a70d8325980040861472a',
    messagingSenderId: '372532983327',
    projectId: 'cats-app-25190',
    authDomain: 'cats-app-25190.firebaseapp.com',
    databaseURL: 'https://cats-app-25190-default-rtdb.firebaseio.com',
    storageBucket: 'cats-app-25190.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrBIUIeByjN3mRFEqvZkk2Oslw2-g5rDU',
    appId: '1:372532983327:android:25fc202b1a7912f361472a',
    messagingSenderId: '372532983327',
    projectId: 'cats-app-25190',
    databaseURL: 'https://cats-app-25190-default-rtdb.firebaseio.com',
    storageBucket: 'cats-app-25190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3r8Ma9g4TsHVIpHQ_c9GY6mFaNRxTmjw',
    appId: '1:372532983327:ios:b0b1bbd48cb7820461472a',
    messagingSenderId: '372532983327',
    projectId: 'cats-app-25190',
    databaseURL: 'https://cats-app-25190-default-rtdb.firebaseio.com',
    storageBucket: 'cats-app-25190.appspot.com',
    iosClientId: '372532983327-2l0tnru4bm5l2lsutapc2a15a5bf74lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.catsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3r8Ma9g4TsHVIpHQ_c9GY6mFaNRxTmjw',
    appId: '1:372532983327:ios:b0b1bbd48cb7820461472a',
    messagingSenderId: '372532983327',
    projectId: 'cats-app-25190',
    databaseURL: 'https://cats-app-25190-default-rtdb.firebaseio.com',
    storageBucket: 'cats-app-25190.appspot.com',
    iosClientId: '372532983327-2l0tnru4bm5l2lsutapc2a15a5bf74lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.catsApp',
  );
}
